/**
* @date 2022
* @description This is a Global constant for containers.
*  Each static string constant is getting used in NAC test classes
* @group Testing util
*/

public class NAC_Global_Constants {

    public static String DEFAULT_STOREFRONT_NAME = 'DefaultStore';
    public static String DEFAULT_PROFILE_NAME = 'NAC Customer Community Profile';
    public static String ADMIN_PROFILE_NAME = 'System Administrator';
    public static String DEFAULT_PRODUCT_TYPE = 'Product';
    public static String DEFAULT_PRODUCT_STATUS = 'Released'; 
    public static String DEFAULT_UOM = 'EACH';
    public static Decimal DEFAULT_PRICE = 0;
    public static String DEFAULT_COMMUNITY_NAME_NAC=Label.NAOCAP_Test_Class_Store_Name;    
    public static string STATIC_RESOURCE_NAME='NAC_Bulk_Upload_Template';
    public static string DISPLAY_RECENT_PRODUCTS='displayRecentlyOrderedProducts';
    public static string USD_CURRENCY_CODE='USD';
    public static string DEALER_CATALOG_LABEL='Dealer Catalog';
    public static string PRODUCT_LABEL='Dealer Catalog';
    public static string STRIKETHROUGH_PRICEBOOK= Label.NAOCAP_StandardPricebook;
    public static string NAMEVAR='Test Acc';
    public static string ACTIVECARTID='active';
    public static string WAREHOUSEDEF='ATL';
}